# This is a Kubernete file for setting up a users service for example.
# Don't use this file in production without proper security measures.

apiVersion: v1
kind: Namespace
metadata:
  name: users
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config-map
  namespace: users
data:
  SERVER_PORT: "8080"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_NAME: "user_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: users
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "admin"
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-app
  namespace: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      name: users
      labels:
        app: users
    spec:
      automountServiceAccountToken: false
      containers:
        - name: users-container
          image: ivanwilhelm/users-service:latest
          envFrom:
            - configMapRef:
                name: users-config-map
            - secretRef:
                name: users-secret
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: "1Gi"
            limits:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: "5Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: users
spec:
  type: LoadBalancer
  selector:
    app: users
  ports:
    - port: 8080
      targetPort: 8080
