name: users_service
description: This service is responsible for managing users.
version: 1.0.0
repository: https://github.com/euivanw/users-service
environment:
  sdk: ^3.7.1

dependencies:
  args: ^2.7.0
  dart_either: ^2.0.0
  logging: ^1.3.0
  postgres: ^3.5.5
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  uuid: ^4.5.1

dev_dependencies:
  http: ^1.3.0
  lints: ^5.1.1
  test: ^1.25.15
