Project users {
    database_type: 'PostgreSQL'
}

Table migration {
    id uuid [not null]
    name varchar(150) [not null]
    sql text [not null]
    migrated_at timestamp [not null, default: `now()`]

    indexes {
        id [pk]
    }
}

Table users {
    id uuid [not null]
    first_name varchar(50) [not null]
    last_name varchar(50) [not null]
    email varchar(150) [not null]
    created_at timestamp [not null, default: `now()`]
    updated_at timestamp

    indexes {
        id [pk]
        first_name [name: 'idx_users_first_name']
        last_name [name: 'idx_users_last_name']
        email [unique, name: 'idx_users_email']
    }
}
