Project users {
    database_type: 'PostgreSQL'
}

Table migration {
    id uuid [not null]
    name varchar(150) [not null]
    sql text [not null]
    migrated_at timestamp [not null, default: `now()`]

    indexes {
        id [pk]
    }
}
