name: "Development CI"

on:
  pull_request:
    branches: [ "*" ]

jobs:
  analyze:
    name: "Analyze"
    uses: ./.github/workflows/analyze.yaml
    with:
      sdk-version: ${{ vars.DART_SDK_VERSION }}

  tests:
    name: "Tests"
    uses: ./.github/workflows/test.yaml
    with:
      sdk-version: ${{ vars.DART_SDK_VERSION }}

  sonar:
    name: "SonarQube"
    needs: [ analyze, tests ]
    uses: ./.github/workflows/sonar.yaml

  build:
    name: "Build"
    needs: [ sonar ]
    uses: ./.github/workflows/build.yaml
    secrets:
      docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
    with:
      tag-name: ${{ vars.DOCKERHUB_TAG }}
      tag-version: SNAPSHOT-${{ github.run_id }}
      container-platforms: ${{ vars.DOCKER_PLATFORMS }}
      push-to-registry: false
