name: Update Version

on:
  workflow_call:
    inputs:
      tag-version:
        type: string
        required: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: '22'

      - name: Update version in pubspec.yaml
        run: |
          sed -i 's/version: [0-9]*\.[0-9]*\.[0-9]*/version: '"${TAG_VERSION}"'/' pubspec.yaml
        env:
          TAG_VERSION: ${{ inputs.tag-version }}

      - name: Update version in changelog
        run: |
          sed -i 's/## \[Unreleased\]/## \[Unreleased\]\n\n## [v'"${TAG_VERSION}"'] - '"$(date +'%Y-%m-%d')"'/g' CHANGELOG.md
        env:
          TAG_VERSION: ${{ inputs.tag-version }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pubspec.yaml
          git add CHANGELOG.md
          git commit -m "chore: Bump version to ${{ inputs.tag-version }}"
          git push

      - name: Create Git Tag for the new version
        run: |
          git tag -a "v${{ inputs.tag-version }}" -m "Release v${{ inputs.tag-version }}"
          git push origin "v${{ inputs.tag-version }}"
        env:
          TAG_VERSION: ${{ inputs.tag-version }}
